[package]
name = "fuzzy"
version = "0.1.0"
authors = ["David Judge <biro97@gmail.com>"]
edition = "2018"

[lib]
name = "fuzzy"
crate-type = ["cdylib"]

[dependencies]
neon = { git = "https://github.com/neon-bindings/neon"}